# Generated by Django 5.2.10 on 2026-02-05 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applicant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('PATIENT_ID', 'Documento com foto do paciente'), ('APPLICANT_ID', 'Documento com foto do solicitante'), ('MARRIAGE_CERTIFICATE', 'Certidão de casamento / União estável'), ('POWER_OF_ATTORNEY', 'Procuração específica')], max_length=40, verbose_name='Tipo de documento')),
                ('file', models.FileField(upload_to='applicants/documents/%Y/%m/', verbose_name='Arquivo')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='applicant.applicant')),
            ],
            options={
                'verbose_name': 'Documento do solicitante',
                'verbose_name_plural': 'Documentos do solicitante',
            },
        ),
    ]
