# Generated by Django 5.2.10 on 2026-04-29 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant_document', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantdocument',
            name='document_type',
            field=models.CharField(choices=[('PATIENT_ID', 'Documento com foto do paciente'), ('APPLICANT_ID', 'Documento com foto do solicitante'), ('MARRIAGE_CERTIFICATE', 'Certidão de casamento / União estável'), ('POWER_OF_ATTORNEY', 'Procuração específica'), ('DEATH_CERTIFICATE', 'Certidão de Óbito')], max_length=40, verbose_name='Tipo de documento'),
        ),
    ]
