# Generated by Django 5.2.10 on 2026-02-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol', models.CharField(blank=True, db_column='protocolo', max_length=20, unique=True)),
                ('purpose', models.CharField(choices=[('OBITO', 'Óbito'), ('DPVAT', 'DPVAT'), ('INSS', 'Benefício INSS'), ('SEGURO', 'Seguro'), ('INVENTARIO', 'Inventário'), ('ACAO_JUDICIAL', 'Ação Judicial'), ('OUTROS', 'Outros')], db_column='finalidade', max_length=20, verbose_name='Finalidade da Documentação')),
                ('other_purpose', models.CharField(blank=True, db_column='outro_motivo', max_length=255, null=True, verbose_name='Outro motivo')),
                ('status', models.CharField(choices=[('aguardando', 'Aguardando'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado')], db_column='status', default='aguardando', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='criado_em', verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='atualizado_em', verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Solicitação de Documento',
                'verbose_name_plural': 'Solicitações de Documento',
                'db_table': 'pedido_documento',
            },
        ),
    ]
