# Generated by Django 5.2.10 on 2026-03-23 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_request', '0002_remove_documentrequest_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('aguardando', 'Aguardando'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado')], db_column='status', default='aguardando', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='criado_em', verbose_name='Criado em')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='document_request.documentrequest')),
            ],
        ),
    ]
