# Generated by Django 5.2.10 on 2026-03-30 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_request', '0004_documentstatus_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentstatus',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
