# Generated by Django 5.2.10 on 2026-04-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_request', '0005_alter_documentstatus_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentrequest',
            name='purpose',
            field=models.CharField(choices=[('OBITO', 'Óbito'), ('DPVAT', 'DPVAT'), ('INSS', 'Benefício INSS'), ('SEGURO', 'Seguro'), ('INVENTARIO', 'Inventário'), ('ACAO JUDICIAL', 'Ação Judicial'), ('OUTROS', 'Outros')], db_column='finalidade', max_length=20, verbose_name='Finalidade da Documentação'),
        ),
    ]
