# Generated by Django 5.2.10 on 2026-06-23 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_request', '0006_alter_documentrequest_purpose'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentstatus',
            options={'ordering': ['created_at'], 'verbose_name': 'Status do Documento', 'verbose_name_plural': 'Status dos Documentos'},
        ),
        migrations.AlterField(
            model_name='documentstatus',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='documentstatus',
            table='status_documento',
        ),
    ]
