# Generated by Django 5.2.10 on 2026-07-09 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_request', '0007_status_meta_ordering_set_null'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentRectification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_cpf', models.CharField(db_column='cpf_confirmacao', help_text='CPF informado para confirmar a identidade de quem solicitou a retificação.', max_length=14, verbose_name='CPF de confirmação')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='criado_em', verbose_name='Criado em')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rectifications', to='document_request.documentrequest')),
            ],
            options={
                'verbose_name': 'Retificação de Documento',
                'verbose_name_plural': 'Retificações de Documento',
                'db_table': 'retificacao_documento',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentRectificationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('solicitada', 'Solicitada'), ('agendada', 'Agendada'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], db_column='status', default='solicitada', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='criado_em', verbose_name='Criado em')),
                ('rectification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='document_request.documentrectification')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Status da Retificação',
                'verbose_name_plural': 'Status das Retificações',
                'db_table': 'status_retificacao',
                'ordering': ['created_at'],
            },
        ),
    ]
