# Generated by Django 5.2.10 on 2026-07-10 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_request', '0008_documentrectification_documentrectificationstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrectification',
            name='reason',
            field=models.TextField(db_column='motivo_retificacao', default='', help_text='Descrição do motivo da retificação fornecida pelo solicitante.', max_length=500, verbose_name='Motivo da retificação'),
        ),
    ]
