# Generated by Django 5.2.10 on 2026-02-05 14:33

import django.core.validators
import django.db.models.deletion
import utils.applicant_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('document_request', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_type', models.CharField(choices=[('PATIENT', 'Paciente'), ('REPRESENTATIVE', 'Representante')], db_column='tipo_solicitante', help_text='Informe se o solicitante é o próprio paciente ou um representante.', max_length=20, verbose_name='Solicitante é')),
                ('relationship_degree', models.CharField(blank=True, choices=[('FAMILY', 'Pais / Demais familiares'), ('SPOUSE', 'Cônjuge ou Companheiro'), ('ATTORNEY', 'Procurador')], db_column='grau_parentesco', help_text='Obrigatório apenas quando o solicitante for um representante.', max_length=20, null=True, verbose_name='Grau de parentesco')),
                ('full_name', models.CharField(db_column='nome', help_text='Nome completo do solicitante.', max_length=255, verbose_name='Nome')),
                ('cpf', models.CharField(db_column='cpf', help_text='CPF do solicitante.', max_length=14, validators=[utils.applicant_utils.validar_cpf], verbose_name='CPF')),
                ('rg', models.CharField(db_column='rg', help_text='RG do solicitante', max_length=20, validators=[utils.applicant_utils.validar_rg], verbose_name='RG')),
                ('email', models.EmailField(db_column='email', help_text='Endereço de e-mail para contato.', max_length=254, validators=[django.core.validators.EmailValidator(message='Informe um e-mail válido.')], verbose_name='E-mail')),
                ('address', models.TextField(db_column='endereco', help_text='Endereço completo do solicitante.', verbose_name='Endereço')),
                ('phone', models.CharField(db_column='telefone', help_text='Telefone para contato.', max_length=20, validators=[utils.applicant_utils.validar_celular], verbose_name='Telefone')),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='document_request.documentrequest')),
            ],
            options={
                'verbose_name': 'Solicitante',
                'verbose_name_plural': 'Solicitantes',
                'db_table': 'solicitante',
            },
        ),
    ]
