# Generated by Django 5.2.10 on 2026-06-25 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='address',
            field=models.CharField(db_column='endereco', help_text='Endereço completo do solicitante.', max_length=500, verbose_name='Endereço'),
        ),
    ]
