# Generated by Django 5.2.10 on 2026-02-05 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('document_request', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_column='data_ocorrencia', verbose_name='Data da ocorrência')),
                ('time', models.TimeField(db_column='hora_ocorrencia', verbose_name='Hora da ocorrência')),
                ('patient_name', models.CharField(db_column='paciente_nome', max_length=150, verbose_name='Paciente')),
                ('city', models.CharField(choices=[('BELFORD ROXO', 'BELFORD ROXO'), ('DUQUE DE CAXIAS', 'DUQUE DE CAXIAS'), ('ITAGUAÍ', 'ITAGUAÍ'), ('JAPERI', 'JAPERI'), ('MAGE', 'MAGE'), ('MESQUITA', 'MESQUITA'), ('NILÓPOLIS', 'NILÓPOLIS'), ('NOVA IGUAÇU', 'NOVA IGUAÇU'), ('PARACAMBI', 'PARACAMBI'), ('QUEIMADOS', 'QUEIMADOS'), ('SAO JOAO DE MERITI', 'SAO JOAO DE MERITI'), ('SEROPÉDICA', 'SEROPÉDICA')], db_column='municipio', max_length=30, verbose_name='Município')),
                ('neighborhood', models.CharField(db_column='bairro', max_length=100, verbose_name='Bairro')),
                ('address', models.CharField(db_column='endereco', max_length=200, verbose_name='Endereço')),
                ('reason', models.CharField(db_column='motivo_solicitacao', help_text='Máximo de 50 caracteres', max_length=50, verbose_name='Motivo da solicitação da ambulância')),
                ('attendance_location', models.CharField(choices=[('RES', 'Residência'), ('PUB', 'Via Pública'), ('OTH', 'Outro')], db_column='local_atendimento', max_length=3, verbose_name='Local do atendimento')),
                ('other_location_description', models.CharField(blank=True, db_column='outro_local', help_text="Preencher apenas se 'Outro' for selecionado", max_length=100, null=True, verbose_name='Outro local')),
                ('occurrence_number', models.CharField(blank=True, db_column='numero_ocorrencia', max_length=30, null=True, verbose_name='Número da ocorrência')),
                ('notes', models.CharField(blank=True, db_column='observacoes', help_text='Máximo de 150 caracteres', max_length=150, null=True, verbose_name='Observações')),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='document_request.documentrequest')),
            ],
            options={
                'verbose_name': 'Ocorrência',
                'verbose_name_plural': 'Ocorrências',
                'db_table': 'ocorrencia',
                'ordering': ['-date', '-time'],
            },
        ),
    ]
