# Generated by Django 5.2.10 on 2026-02-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProtocolCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_column='ano', unique=True)),
                ('last_number', models.IntegerField(db_column='ultimo_numero', default=0)),
            ],
        ),
    ]
